### ISSUE TITLE
HTTP headers and remove ip

### ISSUE THREAD

**Issue by stiv-yakovenko** [timhuijgen/sockjs-wrap#3]
Is it possible to get HTTP request headers and remote ip during authentication?        connection.on('authenticate', function (data, callback) {
            // I need ip here
        });

**Comment by timhuijgen** [comment]
```
// Connection fires authenticated event when successful
Connection.on('authenticated', function(user){
    // Do anything you want

   // You can get the original sockjs connection object like this:
   var sockjs_obj = user.getConnection();
  // Now you have access to all the info.
   console.log( sockjs_obj.headers );
   console.log( sockjs_obj.remoteAddress );
});
```

Please mail (timhuijgen@gmail.com) any further questions regarding the library instead of making new issues, unless it really is an issue.
